### PR TITLE
Weights cleanup

### PR DESCRIPTION
**Pull request by zctao**
Refactor and clean up some parts of the code that deals with weights:
- OmniFoldwBkg no longer contains weights and arrays for training and reweighting. All of these are accessed via the data handlers.
- Unfolded weights are now scale factors that should be applied to the prior weights instead of the final truth-level event weights.
- Add back an argument '--load-models <output/dir/containing/model/checkpoints>' for unfold.py to load trained models for reweighting

### CODE REVIEW

**Comment by zctao** [comment]
@wecassidy

**Comment by wecassidy** [comment]
Quick question - if I want to reuse unfolding results, is this the correct workflow:

* For results computed *before* this PR, use `--load-models`
* For results computed *after* this PR, use `--load-models` to use pretrained models, or `--unfolded-weights` to use precomputed weights, but not both

**Comment by zctao** [comment]
Yes. 
If `--unfolded-weights` is provided, `--load-models`, as well as many other arguments that are used in OmniFoldwBkg.run, is ignored. With `--unfolded-weights`, basically `unfold.py` only plots the result with the provided weights.

**Comment by wecassidy** [comment]
Got it. I wonder if it makes sense to split out unfolding and plotting into two scripts. The workflow would be:
```
$ python unfold.py [options]
$ python plotting.py [options]
```
That simplify the CLI, since there are options that only make sense for unfolding and arguments that only make sense for plotting. And decoupling unfolding code and plotting code is conceptually nice to me.

On the other hand there are shared options between unfolding and plotting (`-tsd`, to name a few) and repetition leads to bugs. Maybe unfolding could produce a "results file" with the values of the shared options that could be passed to plotting? Then the workflow would become:
```
$ python unfold.py [options]
$ python plotting.py [options] result-file
```
or even (if the results file is sent to stdout as well as a normal file)
```
$ python unfold.py [options] | python plotting.py [options]
```

**Comment by zctao** [comment]
Yeah splitting the unfolding and plotting scripts sounds nice. Maybe one complication is that the preprocessing of input arrays and weights are shared by the unfolding and plotting steps, and it would be nice to not repeat it.

**Pull request merged**
